AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "hubstep.gemspec"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
