AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "hubstep.gemspec"

Metrics/LineLength:
  Max: 100

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
